name: "Olivier Bourgain"
description: ""

url: "www.obourgain.com/blog/"
baseurl: "www.obourgain.com/blog/"
permalink: /blog/:year/:month/:day/:title.html

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
