name: "Olivier Bourgain"
description: ""

url: "www.obourgain.com/blog/"
baseurl: ""


permalink: /blog/:year/:month/:day/:title.html


markdown: rdiscount
permalink: pretty
highlighter: pygments
#paginate: 10
